# Generated by Django 3.0.5 on 2021-01-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210117_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttitle',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
